spring:
  sql:
    init:
      mode: always # This ensures the initialization scripts are always run on startup
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/telcoprod
    username: telco
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

props:
  testData1: testData1