spring:
  profiles:
    active: jms-listener
  sql:
    init:
      mode: always # This ensures the initialization scripts are always run on startup
  datasource:
    url: jdbc:postgresql://localhost:5432/telco
    username: telco
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
  artemis:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
#   jms:
#     template:
#       default-destination: clientcloud.create.queue

# # spring:
#   profiles:
#     active:
#     - prod